apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-postgresdb-persistent-volume
  namespace: mbackstage
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-persistent-volume-claim
  namespace: mbackstage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: mbackstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:13.2-alpine
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: m-db-persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: mbackstage
  labels:
    app: postgresdb
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgresdb
